### ISSUE TITLE
Error reporting returns HTTP 400 status code

### ISSUE THREAD

**Issue by RobbinHabermehl** [vanjacosic/opbeat-js#2]
The example within this repository isn't working as expected; none of the three test errors gets reported to Opbeat successfully as each call is considered a "bad request".

One of the (decoded) URL's is as follows:

https://opbeat.com/api/v1/organizations/${ORG_ID}/apps/${APP_ID}/errors.gif?data={"client_version":"opbeat-js/0.0.1","logger":"javascript","http":{"url":"file:///path/to/example.html","headers":{"User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.6.3 (KHTML, like Gecko) Version/8.0.6 Safari/600.6.3"}},"exception":{"value":"ReferenceError: Can't find variable: derp"},"stacktrace":{"frames":[{"filename":"file:///path/to/example.html","lineno":42,"function":"?","in_app":true}]},"culprit":"file:///path/to/example.html","message":"ReferenceError: Can't find variable: derp","client_supplied_id":"06c54188b6d24324aa34896f119ec4a1"}

Probably the interface has changed since this repository has been created. I'm hoping this can be updated so I can start using Opbeat for front-end as well and I'd be happy to help out in order to achieve this!

**Comment by vanjacosic** [comment]
This issue was fixed more than a month ago via Opbeat support. Closing.
